name: Cleanup Stale Branches

on:
  schedule:
    # Runs at 00:00 every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  delete_old_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch --all

      - name: Delete stale branches
        run: |
          # Get the date 7 days ago in YYYY-MM-DD format
          seven_days_ago=$(date -d '7 days ago' +%Y-%m-%d)

          # List branches that haven't been updated in the last 7 days
          for branch in $(git for-each-ref --format='%(refname:short) %(committerdate:short)' refs/remotes/origin | awk -v date="$seven_days_ago" '$2 <= date {print $1}'); do
            # Ensure the branch is not 'main', 'master', or any protected branches
            if [[ "$branch" != "origin/main" && "$branch" != "origin/master" && "$branch" != *"HEAD"* ]]; then
              git push origin --delete ${branch#origin/}
              echo "Deleted branch $branch"
            fi
          done

      - name: Cleanup
        run: git remote prune origin
